siteName: Perennial Weaver
author: David White
poweredBy: Kabooly
poweredByUrl: https://kabooly.com
email: perennialweaver@btinternet.com
phoneNumber: "07950172499"
addressLineOne: Flat 4
addressLineTwo: Simba Court
addressLineThree: 71 Lion Road
townCity: Twickenham
region: London
postCode: TW1 4HT
locationLatLong: 51.447192891989765, -0.3377632367984757
country: "GB"
googleOpeningMonday: "09:00"
googleClosingMonday: "17:00"
googleOpeningTuesday: "09:00"
googleClosingTuesday: "17:00"
googleOpeningWednesday: "09:00"
googleClosingWednesday: "17:00"
googleOpeningThursday: "09:00"
googleClosingThursday: "17:00"
googleOpeningFriday: "09:00"
googleClosingFriday: "17:00"
googleOpeningSaturday: "09:00"
googleClosingSaturday: "17:00"
