siteName: Slot Picks
author: David White
poweredByOne: Kabooly
poweredByTwo: Arragon Affiliates
poweredByOneUrl: https://kabooly.com/
poweredByTwoUrl: https://arragonaffiliates.com/
email: david@kabooly.com
phoneNumber: "07877304672"
strapLine: "Top UK Slots & Casinos Reviewed"