backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
media_folder: "src/_includes/static/img"
public_folder: "/_includes/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "snippets"
    label: "Snippets"
    files:
      - label: "Homepage Content"
        name: "homepage"
        file: "src/_data/seoIntroText.yaml"  # Path to the YAML file
        fields:
          - label: "SEO Intro Text"
            name: "seoIntroText"
            widget: "list"
            fields:
              - { label: "Heading", name: "heading", widget: "string", required: false }
              - label: "Paragraphs"
                name: "paragraphs"
                widget: "list"
                field: { label: "Paragraph", name: "paragraph", widget: "text" }
      - label: "Retreats Content"
        name: "retreats"
        file: "src/_data/retreatsIntroText.yaml"  # Path to the YAML file
        fields:
          - label: "Retreats Intro Text"
            name: "retreatsIntroText"
            widget: "markdown"
  - label: "Article"
    name: "articles"
    folder: "src/articles"
    create: true
    fields:
      - {
        label: "Title",
        name: "title",
        widget: "string",
        hint: "*This title will be used in the page's H1 tag, and also determines the URL (between 20 and 70 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{20,70}$', "Must be between 20 and 70 characters"]
      }
      - { 
        label: "SEO Title",
        name: "seoTitle",
        widget: "string",
        hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
      }
      - {
        label: "Description",
        name: "description",
        widget: "string",
        hint: "*Used in search engines (between 70 and 155 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{70,155}$', "Must be between 70 and 155 characters"]
      }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Show Date?", name: "showDate", widget: "boolean", default: false, required: false }
      - {
        label: "Image for SEO",
        name: "imageForSeo",
        widget: "image",
        hint: "*This is required, just use any image that you have used in the main body of the article (Use 4:3 ratio, e.g. 600px x 450px)"
      }
      - {
        label: "Image Alt",
        name: "imageAlt",
        widget: "string"
      }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "type"
        name: "type"
        create: true
        options: ["article", "privacy"]
        default: "article"
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["article", "privacy", "faq", "news"]
        default: ["article"]
  - label: "Settings"
    name: "settings"
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: firstLevelItems
            widget: list
            collapsed: false
            allow_add: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
              - label: Nav Items
                name: secondLevelItems
                widget: list
                collapsed: true
                fields:
                  - { label: Title, name: text, widget: string }
                  - { label: URL, name: url, widget: string }
              
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Site Name, name: siteName, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: Powered by, name: poweredBy, widget: string }          
          - { label: Powered by URL, name: poweredByUrl, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Phone number, name: phoneNumber, widget: string }
  - label: "SEO"
    name: "seo"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "src/_data/homepageSeo.yaml"
        fields:
          - {
            label: "Title",
            name: "title",
            widget: "string",
            hint: "*This title will be used in the page's H1 tag, and also determines the URL (between 20 and 70 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{20,70}$', "Must be between 20 and 70 characters"]
          }
          - { 
            label: "SEO Title",
            name: "seoTitle",
            widget: "string",
            hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
          }
          - {
            label: "Description",
            name: "description",
            widget: "string",
            hint: "*Used in search engines (between 70 and 155 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{70,155}$', "Must be between 70 and 155 characters"]
          }
      - label: "Contact"
        name: "contact"
        file: "src/_data/contactSeo.yaml"
        fields:
          - {
            label: "Title",
            name: "title",
            widget: "string",
            hint: "*This title will be used in the page's H1 tag, and also determines the URL (between 20 and 70 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{20,70}$', "Must be between 20 and 70 characters"]
          }
          - { 
            label: "SEO Title",
            name: "seoTitle",
            widget: "string",
            hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
          }
          - {
            label: "Description",
            name: "description",
            widget: "string",
            hint: "*Used in search engines (between 70 and 155 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{70,155}$', "Must be between 70 and 155 characters"]
          }
      - label: "Retreats"
        name: "retreats"
        file: "src/_data/retreatsSeo.yaml"
        fields:
          - {
            label: "Title",
            name: "title",
            widget: "string",
            hint: "*This title will be used in the page's H1 tag, and also determines the URL (between 20 and 70 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{20,70}$', "Must be between 20 and 70 characters"]
          }
          - { 
            label: "SEO Title",
            name: "seoTitle",
            widget: "string",
            hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
          }
          - {
            label: "Description",
            name: "description",
            widget: "string",
            hint: "*Used in search engines (between 70 and 155 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{70,155}$', "Must be between 70 and 155 characters"]
          }
  - label: "Components"
    name: "components"
    files:
      - label: "FAQs"
        name: "faqs"
        file: "src/_data/faqsData.yaml"
        fields:
          - label: FAQ Items
            name: faqs
            widget: list
            collapsed: false
            fields:
              - { label: Question, name: question, widget: string }
              - { label: Answer, name: answer, widget: string }
      - label: "Home Hero"
        name: "homeHero"
        file: "src/_data/homeHero.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Sub title, name: subTitle, widget: string }
      - label: "Contact Hero"
        name: "contactHero"
        file: "src/_data/contactHero.yaml"
        fields:
          - { label: Sub title, name: subTitle, widget: string }
          - { label: Phone number, name: phoneNumber, widget: string }
      - label: "Retreats Hero"
        name: "retreatsHero"
        file: "src/_data/retreatsHero.yaml"
        fields:
          - { label: Sub title, name: subTitle, widget: string }          
      - label: "One to One Therapy"
        name: "oneToOneTherapy"
        file: "src/_data/oneToOneTherapy.yaml"
        fields:
          - { label: "H2 Title", name: "title", widget: "string" }
          - label: "Content"
            name: "content"
            widget: "markdown"
          - { label: "Link Href", name: "linkHref", widget: "string" }
          - { label: "Link Text", name: "linkText", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Image Alt", name: "imageAlt", widget: "string" }
          - { 
            label: "Image Width", 
            name: "imageWidth", 
            widget: "number", 
            default: 0, 
            hint: "Recommended width is 600px" 
          }
          - { 
            label: "Image Height", 
            name: "imageHeight", 
            widget: "number", 
            default: 0, 
            hint: "Recommended height is 450px" 
          }
          - { label: "Is Image Rounded?", name: "isImageRounded", widget: "boolean", default: false }
          - widget: select
            label: "Image Position"
            name: "imagePosition"
            options: ["left", "right"]
            default: "left"
      - label: "Events"
        name: "events"
        file: "src/_data/events.yaml"
        fields:
          - { label: "H2 Title", name: "title", widget: "string" }
          - label: "Content"
            name: "content"
            widget: "markdown"
          - { label: "Link Href", name: "linkHref", widget: "string" }
          - { label: "Link Text", name: "linkText", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Image Alt", name: "imageAlt", widget: "string" }
          - { 
            label: "Image Width", 
            name: "imageWidth", 
            widget: "number", 
            default: 0, 
            hint: "Recommended width is 600px" 
          }
          - { 
            label: "Image Height", 
            name: "imageHeight", 
            widget: "number", 
            default: 0, 
            hint: "Recommended height is 450px" 
          }
          - { label: "Is Image Rounded?", name: "isImageRounded", widget: "boolean", default: false }
          - widget: select
            label: "Image Position"
            name: "imagePosition"
            options: ["left", "right"]
            default: "left"
      - label: "Retreats"
        name: "retreats"
        file: "src/_data/retreats.yaml"
        fields:
          - { label: "H2 Title", name: "title", widget: "string" }
          - label: "Content"
            name: "content"
            widget: "markdown"
          - { label: "Link Href", name: "linkHref", widget: "string" }
          - { label: "Link Text", name: "linkText", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Image Alt", name: "imageAlt", widget: "string" }
          - { 
            label: "Image Width", 
            name: "imageWidth", 
            widget: "number", 
            default: 0, 
            hint: "Recommended width is 600px" 
          }
          - { 
            label: "Image Height", 
            name: "imageHeight", 
            widget: "number", 
            default: 0, 
            hint: "Recommended height is 450px" 
          }
          - { label: "Is Image Rounded?", name: "isImageRounded", widget: "boolean", default: false }
          - widget: select
            label: "Image Position"
            name: "imagePosition"
            options: ["left", "right"]
            default: "left"
      - label: "Breathwork and Meditation"
        name: "breathworkAndMeditation"
        file: "src/_data/breathworkAndMeditation.yaml"
        fields:
          - { label: "H2 Title", name: "title", widget: "string" }
          - label: "Content"
            name: "content"
            widget: "markdown"
          - { label: "Link Href", name: "linkHref", widget: "string" }
          - { label: "Link Text", name: "linkText", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Image Alt", name: "imageAlt", widget: "string" }
          - { 
            label: "Image Width", 
            name: "imageWidth", 
            widget: "number", 
            default: 0, 
            hint: "Recommended width is 600px" 
          }
          - { 
            label: "Image Height", 
            name: "imageHeight", 
            widget: "number", 
            default: 0, 
            hint: "Recommended height is 450px" 
          }
          - { label: "Is Image Rounded?", name: "isImageRounded", widget: "boolean", default: false }
          - widget: select
            label: "Image Position"
            name: "imagePosition"
            options: ["left", "right"]
            default: "left"
      - label: "About"
        name: "about"
        file: "src/_data/about.yaml"
        fields:
          - { label: "H2 Title", name: "title", widget: "string" }
          - label: "Content"
            name: "content"
            widget: "markdown"
          - { label: "Link Href", name: "linkHref", widget: "string" }
          - { label: "Link Text", name: "linkText", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Image Alt", name: "imageAlt", widget: "string" }
          - { 
            label: "Image Width", 
            name: "imageWidth", 
            widget: "number", 
            default: 0, 
            hint: "Recommended width is 600px" 
          }
          - { 
            label: "Image Height", 
            name: "imageHeight", 
            widget: "number", 
            default: 0, 
            hint: "Recommended height is 450px" 
          }
          - { label: "Is Image Rounded?", name: "isImageRounded", widget: "boolean", default: false }
          - widget: select
            label: "Image Position"
            name: "imagePosition"
            options: ["left", "right"]
            default: "left"
      - label: "Contact"
        name: "contact"
        file: "src/_data/contact.yaml"
        fields:
          - { label: "H2 Title", name: "title", widget: "string" }
          - label: "Content"
            name: "content"
            widget: "markdown"
          - { label: "Link Href", name: "linkHref", widget: "string" }
          - { label: "Link Text", name: "linkText", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Image Alt", name: "imageAlt", widget: "string" }
          - { 
            label: "Image Width", 
            name: "imageWidth", 
            widget: "number", 
            default: 0, 
            hint: "Recommended width is 600px" 
          }
          - { 
            label: "Image Height", 
            name: "imageHeight", 
            widget: "number", 
            default: 0, 
            hint: "Recommended height is 450px" 
          }
          - { label: "Is Image Rounded?", name: "isImageRounded", widget: "boolean", default: false }
          - widget: select
            label: "Image Position"
            name: "imagePosition"
            options: ["left", "right"]
            default: "left"
