backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
media_folder: "src/_includes/static/img"
public_folder: "/_includes/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Homepage Content"
        name: "homepage"
        file: "src/_data/seoIntroText.yaml"  # Path to the YAML file
        fields:
          - label: "SEO Intro Text"
            name: "seoIntroText"
            widget: "list"
            fields:
              - { label: "Heading", name: "heading", widget: "string", required: false }
              - label: "Paragraphs"
                name: "paragraphs"
                widget: "list"
                field: { label: "Paragraph", name: "paragraph", widget: "text" }
  - label: "Article"
    name: "articles"
    folder: "src/articles"
    create: true
    fields:
      - {
        label: "Title",
        name: "title",
        widget: "string",
        hint: "*This title will be used in the page's H1 tag, and also determines the URL (between 20 and 70 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{20,70}$', "Must be between 20 and 70 characters"]
      }
      - { 
        label: "SEO Title",
        name: "seoTitle",
        widget: "string",
        hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
      }
      - {
        label: "Description",
        name: "description",
        widget: "string",
        hint: "*Used in search engines (between 70 and 155 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{70,155}$', "Must be between 70 and 155 characters"]
      }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Show Date?", name: "showDate", widget: "boolean", default: false, required: false }
      - {
        label: "Image for SEO",
        name: "imageForSeo",
        widget: "image",
        hint: "*This is required, just use any image that you have used in the main body of the article (Use 4:3 ratio, e.g. 600px x 450px)"
      }
      - {
        label: "Image Alt",
        name: "imageAlt",
        widget: "string"
      }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "type"
        name: "type"
        create: true
        options: ["article", "privacy"]
        default: "article"
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["article", "privacy", "faq", "news"]
        default: ["article"]
  - label: "SEO"
    name: "seo"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "src/_data/homepage.yaml"
        fields:
          - {
            label: "Title",
            name: "title",
            widget: "string",
            hint: "*This title will be used in the page's H1 tag, and also determines the URL (between 20 and 70 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{20,70}$', "Must be between 20 and 70 characters"]
          }
          - { 
            label: "SEO Title",
            name: "seoTitle",
            widget: "string",
            hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
          }
          - {
            label: "Description",
            name: "description",
            widget: "string",
            hint: "*Used in search engines (between 70 and 155 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{70,155}$', "Must be between 70 and 155 characters"]
          }
  - label: "Components"
    name: "components"
    files:
      - label: "FAQs"
        name: "faqs"
        file: "src/_data/faqsData.yaml"
        fields:
          - label: FAQ Items
            name: faqs
            widget: list
            collapsed: false
            fields:
              - { label: Question, name: question, widget: string }
              - { label: Answer, name: answer, widget: string }
