backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
media_folder: "src/_includes/static/img"
public_folder: "/_includes/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Article"
    name: "articles"
    folder: "src/articles"
    create: true
    editor:
      preview: false
    fields:
      - {
        label: "Title",
        name: "title",
        widget: "string",
        hint: "*This title will be used in the page's H1 tag, and also determines the URL (between 20 and 70 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{20,70}$', "Must be between 20 and 70 characters"]
      }
      - { 
        label: "SEO Title",
        name: "seoTitle",
        widget: "string",
        hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
      }
      - {
        label: "Description",
        name: "description",
        widget: "string",
        hint: "*Used in search engines (between 70 and 155 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{70,155}$', "Must be between 70 and 155 characters"]
      }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Show Date?", name: "showDate", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "type"
        name: "type"
        create: true
        options: ["article", "privacy"]
        default: "article"
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["article", "privacy", "report", "faq"]
        default: ["article"]
  - label: "Product"
    name: "products"
    folder: "src/products"
    create: true
    editor:
      preview: false
    fields:
      - {
        label: "Title",
        name: "title",
        widget: "string",
        hint: "*This title will be used in the page's H1 tag, and also determines the URL (between 20 and 70 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{20,70}$', "Must be between 20 and 70 characters"]
      }
      - { 
        label: "SEO Title",
        name: "seoTitle",
        widget: "string",
        hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
      }
      - label: "Image"
        name: "image"
        widget: "image"
        choose_url: true
        required: true
        media_library:
          config:
            multiple: true
      - { label: Image alternative text, name: imageAlt, widget: string }
      - {
        label: "Description",
        name: "description",
        widget: "string",
        hint: "*Used in search engines (between 70 and 155 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{70,155}$', "Must be between 70 and 155 characters"]
      }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Price"
        name: "price"
        widget: "number"
        default: 0
        value_type: "int"
      - widget: select
        label: "tags"
        name: "tags"
        create: true
        options: ["Scarves", "Cushions", "Table Matts", "Table Runners", "Glasses Cases", "Bags", "Key Rings", "Lavender Bags", "Bespoke Orders"]
      - widget: select
        label: "type"
        name: "type"
        create: false
        options: ["product"]
        default: "product"
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: firstLevelItems
            widget: list
            collapsed: false
            allow_add: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
              - label: Nav Items
                name: secondLevelItems
                widget: list
                collapsed: true
                fields:
                  - { label: Title, name: text, widget: string }
                  - { label: URL, name: url, widget: string }
              
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Site Name, name: siteName, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: Powered by, name: poweredBy, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Phone number, name: phoneNumber, widget: string }
          - { label: Company number, name: companyNumber, widget: string }
          - { label: Address Line 1, name: addressLineOne, widget: string }
          - { label: Address Line 2, name: addressLineTwo, widget: string }
          - { label: Address Line 3, name: addressLineThree, widget: string }
          - { label: Town/City, name: townCity, widget: string }
          - { label: Region, name: region, widget: string }
          - { label: Post Code, name: postCode, widget: string }
          - { label: Country, name: country, widget: string }
          - { label: Google Opening Monday, name: googleOpeningMonday, widget: string }
          - { label: Google Closing Monday, name: googleClosingMonday, widget: string }
          - { label: Google Opening Tuesday, name: googleOpeningTuesday, widget: string }
          - { label: Google Closing Tuesday, name: googleClosingTuesday, widget: string }
          - { label: Google Opening Wednesday, name: googleOpeningWednesday, widget: string }
          - { label: Google Closing Wednesday, name: googleClosingWednesday, widget: string }
          - { label: Google Opening Thursday, name: googleOpeningThursday, widget: string }
          - { label: Google Closing Thursday, name: googleClosingThursday, widget: string }
          - { label: Google Opening Friday, name: googleOpeningFriday, widget: string }
          - { label: Google Closing Friday, name: googleClosingFriday, widget: string }
          - { label: Google Opening Saturday, name: googleOpeningSaturday, widget: string }
          - { label: Google Closing Saturday, name: googleClosingSaturday, widget: string }
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "homepage"
        file: "src/_data/homepage.yaml"
        fields:
          - { 
            label: "SEO Title",
            name: "seoTitle",
            widget: "string",
            hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
          }
          - {
            label: "Description",
            name: "description",
            widget: "string",
            hint: "*Used in search engines (between 70 and 155 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{70,155}$', "Must be between 70 and 155 characters"]
          }
      - label: "Contact"
        name: "contact"
        file: "src/_data/contact.yaml"
        fields:
          - {
            label: "Title",
            name: "title",
            widget: "string",
            hint: "*This title will be used in the page's H1 tag, and also determines the URL (between 20 and 70 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{20,70}$', "Must be between 20 and 70 characters"]
          }
          - { 
            label: "SEO Title",
            name: "seoTitle",
            widget: "string",
            hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
          }
          - {
            label: "Description",
            name: "description",
            widget: "string",
            hint: "*Used in search engines (between 70 and 155 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{70,155}$', "Must be between 70 and 155 characters"]
          }
  - label: "Components"
    name: "components"
    editor:
      preview: false
    files:
      - label: "Hero"
        name: "hero"
        file: "src/_data/hero.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Sub title, name: subTitle, widget: string }
      - label: "Testimonials"
        name: "testimonials"
        file: "src/_data/testimonials.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Sub Title, name: subTitle, widget: text }
          - label: Testimonial Items
            name: testimonialItems
            widget: list
            collapsed: false
            allow_add: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Quote, name: quote, widget: string }
              - { label: Name, name: name, widget: string }
      - label: "Disclaimer"
        name: "disclaimer"
        file: "src/_data/disclaimer.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Paragraph 1, name: paragraph1, widget: text }
          - { label: Paragraph 2, name: paragraph2, widget: text }
          - { label: Paragraph 3, name: paragraph3, widget: text }
          - { label: Paragraph 4, name: paragraph4, widget: text }
      - label: "Offices"
        name: "offices"
        file: "src/_data/offices.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro text, name: introText, widget: text }
          - { label: Monday Office Hours, name: mondayOfficeHours, widget: string }
          - { label: Tuesday Office Hours, name: tuesdayOfficeHours, widget: string }
          - { label: Wednesday Office Hours, name: wednesdayOfficeHours, widget: string }
          - { label: Thursday Office Hours, name: thursdayOfficeHours, widget: string }
          - { label: Friday Office Hours, name: fridayOfficeHours, widget: string }
          - { label: Saturday Office Hours, name: saturdayOfficeHours, widget: string }
          - { label: Monday Phone Hours, name: mondayPhoneHours, widget: string }
          - { label: Tuesday Phone Hours, name: tuesdayPhoneHours, widget: string }
          - { label: Wednesday Phone Hours, name: wednesdayPhoneHours, widget: string }
          - { label: Thursday Phone Hours, name: thursdayPhoneHours, widget: string }
          - { label: Friday Phone Hours, name: fridayPhoneHours, widget: string }
          - { label: Saturday Phone Hours, name: saturdayPhoneHours, widget: string }
      - label: "Services"
        name: "services"
        file: "src/_data/services.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Sub Title, name: subTitle, widget: string }
          - { label: Intro Text, name: introText, widget: string }
          - label: Service Items
            name: serviceItems
            widget: list
            collapsed: false
            allow_add: true
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Intro Text, name: introText, widget: text }
              - { label: Destination, name: destination, widget: string }
              - label: "Image"
                name: "image"
                widget: "image"
                choose_url: true
                required: false
                media_library:
                  config:
                    multiple: false
                hint: "*Should be 1:1 ratio. Renders at 46px x 46px*"
              - { label: Image alternative text, name: imageAlt, widget: string, required: false }
      - label: "FAQs"
        name: "faqs"
        file: "src/_data/faqsData.yaml"
        fields:
          - label: FAQ Items
            name: faqs
            widget: list
            collapsed: false
            fields:
              - { label: Question, name: question, widget: string }
              - { label: Answer, name: answer, widget: string }
